language: ruby
install:
  - gem install bundler --version '2.1.4'
  - bundle install
cache:
  - bundler
services:
  - postgresql
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake assets:precompile
# script:
#   - bundle exec rspec
after_success:
  - bundle config set deployment 'true'